### ISSUE TITLE
Performance issue - CPU spike when item is selected and wheel is hidden.

### ISSUE THREAD

**Issue by trekze** [softwaretailoring/wheelnav#103]
Hi there

First of all, great library/widget. Saved me a lot of time in my web game when I added emoting.

My users are reporting a weird spike in CPU when a wheel item is selected (at which point I hide the wheel in the DOM). With a fast CPU, a single instance is fine. But on a low-end device, or if you want do this multiple times in a row, you can spike your CPU to 100%. What does the library do the 1 second following a wheel item selection? It seems to cause a crazy CPU spike, as it was stuck in an inifnite loop for that 1 second.

I have removed all event handlers from the wheel action itself, and the CPU spike still occurs when an item is selected. 

Any ideas?

**Comment by trekze** [comment]
Just to add to the above. I've tested this the issue with a default wheel, with two slices, and no custom options passed to it. Still occurs.

**Comment by trekze** [comment]
![image](https://user-images.githubusercontent.com/3520226/130591725-10dd2b29-d747-4f17-82ff-4cd3d63cbab5.png)

Started clicking on the wheel half way through that performance profile.

**Comment by trekze** [comment]
After some investigation in the raphael code, I noticed excessive use of settimeout and requestionanimation frame, so thought of adding the following options to the wheelnav:

```
        wheel1.animatetime = 0;
        wheel1.animateeffect = 'linear';
```

This may have solved it. Will report definitively after testing with end-users.

**Comment by trekze** [comment]
Confirmed fixed. Feel free to close the issue or leave open for exposure.

**Comment by softwaretailoring** [comment]
Hi @hmexx 
Thank you for reported the solution.
Can I check your web game with wheelnav?
I'm curious about it. :)

**Comment by trekze** [comment]
Sure: https://cryptoroyale.one

Right-click to emote.

**Comment by softwaretailoring** [comment]
Thanks! It's cool!
