### ISSUE TITLE
Documentation on hidden content reveal

### ISSUE THREAD

**Issue by aprilshowers92** [softwaretailoring/wheelnav#105]
Hello! I am having trouble getting my wheelnav to act as a functioning menu. My goal is for the menu items to reveal hidden content as in the homepage demo here: https://wheelnavjs.softwaretailoring.net

I have been able to get the onmouseup navigateFunction command working with the default alert demo, but I can't see documentation on how this needs to be edited to reveal and hide content. Can you please point me in the right direction? 

Thank you, wheelnav is epic! :)

**Comment by softwaretailoring** [comment]
You can do anything in navigateFunction, wheelnav is not responsible for it. (And it is not responsible for the content also.)
I suggest using jQuery hide() and show() functions to achieve your needs.
