### ISSUE TITLE
Middle of donut as anchor link

### ISSUE THREAD

**Issue by EphraimB** [softwaretailoring/wheelnav#106]
Clicking the middle of the donut does nothing or functions as a spreader and closes the donut. I want an option to go to a different page like a login page. I want it to function like this example: [https://youtu.be/6wKr68ZB2D0](url)

**Comment by softwaretailoring** [comment]
You can achieve your needs by customizing spreadWheel function here:
https://github.com/softwaretailoring/wheelnav/blob/v1.7.1/js/dist/wheelnav.js#L461
