### ISSUE TITLE
Bug in version the download page takes me to

### ISSUE THREAD

**Issue by EphraimB** [softwaretailoring/wheelnav#107]
There's a bug in v1.7.1 that's been fixed but the current download version still takes me to v1.7.1 when v1.8.0 is out. This should be fixed.

**Comment by softwaretailoring** [comment]
The v1.8.0 isn't out, it's still a release candidate. The latest releases are here: https://github.com/softwaretailoring/wheelnav/releases

**Comment by EphraimB** [comment]
V1.7.1 is buggy.  Links don’t work.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by softwaretailoring** [comment]
What kind of bug do you think?

**Comment by EphraimB** [comment]
There’s a GitHub commit that links have been fixed but it got fixed in a v1.8.0 beta.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by softwaretailoring** [comment]
Please use v1.8.0 beta. I am not planning a new release lately.

**Comment by EphraimB** [comment]
Any plans for a new release. I want to use npm with my react budgeting app but it's still on the buggy 1.7.1.

**Comment by softwaretailoring** [comment]
Sorry, there is no such plan currently.
