### ISSUE TITLE
Raphael old version dependency fails with 'Delete of an unqualified identifier in strict mode"

### ISSUE THREAD

**Issue by zacharygriffee** [softwaretailoring/wheelnav#111]
Would love to use wheelnav, however, the old version of Raphael that wheelnav depends on utilizes a bad usage of delete which they have long-ago fixed. I attempted to try and use a newer version of Raphael with the fix, but obviously that didn't work.  Well I should say, it worked, the wheelnav appeared and spun, etc etc, but threw a bunch of svg related errors I don't completely understand.

Any plans to upgrade Raphael? Or do I look for another nav.

**Comment by softwaretailoring** [comment]
Thanks for reporting it.
I have plans to upgrade, but not with Raphael, but without. But I don't know when I will release it.

So you have to find another nav.
If you find something useful, I'd appreciate it if you posted that here.

**Comment by zacharygriffee** [comment]
Understandable. I been looking for a good radial menu and current other solutions are not up to date so I'm thinking I may have to take on the project myself. If I come up with something good I'll post here
