### ISSUE TITLE
Where is your build system or are you working on v2?

### ISSUE THREAD

**Issue by olso** [softwaretailoring/wheelnav#12]
I had some ideas to fix the performance issues, but first add you build system here or just say what you use.

**Comment by softwaretailoring** [comment]
I updated the readme with my development environment.
What kind of performance issues do you think?

**Comment by udiedrichsen** [comment]
I really like stuff, good job !

I meanly work with meteor. I build a like meteor package for it.
https://github.com/udiedrichsen/wheelnav/

Deploy example at http://wheelnav.meteor.com/

The performance on mobile device (my Chrome Browser on a HTC One M7) is not very good.
Also is the behaviour different on mobile and desktop browser. After selecting an element the wheel collapse on the desktop but not on the mobile browser.

I believe that your package is very interesting for mobile usages.

**Comment by softwaretailoring** [comment]
Thank you for the meteor package and the bug report! I created an issue for it. #13
I tested it on my Windows Phone 8 and wheelnav works fine on it. However the mobile performance needs some improvement. I'm waiting for the contributors... :)

**Comment by JulienJo** [comment]
Yes, performance on my Samsung Galaxy S4 is not good.  :-/

**Comment by softwaretailoring** [comment]
Thanks for feedback!
I have an idea for improve performance, but I'm curious about @olso's ideas too. :)
