### ISSUE TITLE
clickModeSpreadOff doesn't work on Chrome Mobile

### ISSUE THREAD

**Issue by softwaretailoring** [softwaretailoring/wheelnav#13]
After selecting an element the wheel collapse on the desktop but not on the Chrome Mobile browser.

**Comment by softwaretailoring** [comment]
@udiedrichsen I committed a version which works for me on mobile IE, Chrome, Safari.
Please check this in your meteor package.

**Comment by udiedrichsen** [comment]
Perfect, thanks I will try it as soon as possible.

**Comment by udiedrichsen** [comment]
Work now !

Good job. Also the performance is ok now on chrome browser (HTC One M7).

I will update my meteor package next week.

Best wishes and a nice weekend !

**Comment by softwaretailoring** [comment]
Thanks for quick response!
I'm happy that works for you, new release (v1.5.4) has been added and it contains this bug fix.
Thank you for help in the bug removal process. :)
