### ISSUE TITLE
Slow on cell phone browser?

### ISSUE THREAD

**Issue by 6temes** [softwaretailoring/wheelnav#16]
Hi,

I still didn't check deeply in the source code, but realized that the examples are a bit slow when used with the cell phone (Nexus 5 and iPhone 6). Does anyone have experience deploying this module in a responsive website optimized for mobile?

Anyway, thanks for that library. It is really cool!

**Comment by softwaretailoring** [comment]
Thank you for feedback!
There is a link by @manattweb in issue #15, which is working fine on mobile (at least on my Windows Phone 8).
The main issue now is the large icons on wheel (wich has too long svg path), the labels work on mobile phones without lag.
