### ISSUE TITLE
Menu closed by default?

### ISSUE THREAD

**Issue by NickSick** [softwaretailoring/wheelnav#17]
I think that it would be easy but i didn't find something relative in documentation.
So,is possible to keep the nav closed by default?
Also,it seems that the default clockwise behaviour,it stops working after few clicks on nav items.

**Comment by softwaretailoring** [comment]
There was a currentPercent property wich was available for inner logic. Now this property is available from outside, so you can achieve closed wheel with this property before createWheel():
```JS
wheel.currentPercent = 0;
```
Is this working for you?
Can you send me a sample which contains the clockwise issue?

**Comment by NickSick** [comment]
For some reason it doesn't.
I used the generator from your page to create the nav and i don't think i made any major changes.
I'll try it again and search it for a while.
I am working in local enviroment.,this is how the code looks like.

.Html
 <div id='piemenu' data-wheelnav
 data-wheelnav-slicepath='PieSlice'
 data-wheelnav-spreader data-wheelnav-spreaderpath='PieSpreader'
 data-wheelnav-navangle='270'
 data-wheelnav-cssmode 
 data-wheelnav-init>
  <div data-wheelnav-navitemtext='Home' onmouseup='alert("Place your logic here.");'></div>
  <div data-wheelnav-navitemtext='About' onmouseup='alert("Place your logic here.");'></div>
  <div data-wheelnav-navitemtext='Contact' onmouseup='alert("Place your logic here.");'></div>
 <div data-wheelnav-navitemtext='blah' onmouseup='alert("Place your logic here.");'></div>

.Js
piemenu = new wheelnav('piemenu');
piemenu.spreaderInTitle = icon.plus;
piemenu.spreaderOutTitle = icon.cross;
piemenu.clockwise = true;
piemenu.spreaderRadius = piemenu.wheelRadius * 0.13;
piemenu.sliceInitPathFunction = piemenu.slicePathFunction;
piemenu.initPercent = 0.1;
piemenu.wheelRadius = piemenu.wheelRadius * 0.83;
piemenu.currentPercent = 0;
piemenu.createWheel();

I'm using bootstrap 3

**Comment by NickSick** [comment]
For some reason it doesn't.
I used the generator from your page to create the nav and i don't think i made any major changes.
I'll try it again and search it for a while.
I am working in local enviroment.,this is how the code looks like.

.Html
```
<div id='piemenu' data-wheelnav
 data-wheelnav-slicepath='PieSlice'
 data-wheelnav-spreader data-wheelnav-spreaderpath='PieSpreader'
 data-wheelnav-navangle='270'
 data-wheelnav-cssmode 
 data-wheelnav-init>
  <div data-wheelnav-navitemtext='Home' onmouseup='alert("Place your logic here.");'></div>
  <div data-wheelnav-navitemtext='About' onmouseup='alert("Place your logic here.");'></div>
  <div data-wheelnav-navitemtext='Contact' onmouseup='alert("Place your logic here.");'></div>
 <div data-wheelnav-navitemtext='blah' onmouseup='alert("Place your logic here.");'></div>
   </div> 
```
.Js
```
piemenu = new wheelnav('piemenu');
piemenu.spreaderInTitle = icon.plus;
piemenu.spreaderOutTitle = icon.cross;
piemenu.clockwise = true;
piemenu.spreaderRadius = piemenu.wheelRadius * 0.13;
piemenu.sliceInitPathFunction = piemenu.slicePathFunction;
piemenu.initPercent = 0.1;
piemenu.wheelRadius = piemenu.wheelRadius * 0.83;
piemenu.currentPercent = 0;
piemenu.createWheel();
```
I'm using bootstrap 3

**Comment by softwaretailoring** [comment]
Hmm. The above code is working for me. Did you use the latest commit? I didn't create a release for it, so please download the master zip.
I think I understand your clockwise issue. Check this: piemenu.rotateRound = true;
Is it OK now?

**Comment by NickSick** [comment]
I was working with the 1.5..4 version.With the latest commit and your code above,both issues solved.
Thank you for your time!
