### ISSUE TITLE
Add a custom icon with text

### ISSUE THREAD

**Issue by rajukt** [softwaretailoring/wheelnav#18]
Add a custom icon with text

**Comment by softwaretailoring** [comment]
Indeed, it's a good idea. I planned that a navItem can use more navTitle. For example one for icon and another for text.

**Comment by ayyappaappana** [comment]
Is that fixed
createWheel([null, "show", "red", "green", "blue", icon.opensource, icon...... 
I want to add custom Image with custom Text with angle of text also can be mentioned as property.
