### ISSUE TITLE
Improve mobile performance

### ISSUE THREAD

**Issue by softwaretailoring** [softwaretailoring/wheelnav#21]
The main issue now is the large icons on wheel (wich has too long svg's path), the labels work on mobile phones without lag.

**Comment by softwaretailoring** [comment]
Strange behaviour in Google App on iPhone 5C (in Safari and Chrome browsers works well): When I clicked on a section it wasn't always jumping to the one I selected.

**Comment by softwaretailoring** [comment]
Hi @Mubashirkhan 
Can you send sample link where I'll be able to investigate it?

**Comment by Mubashirkhan** [comment]
actually i'm having this issue when trying to load that from an in app browser. I'm trying to integrate that in a react native app and loading the wheelnav examples inside a webview in my app

**Comment by Mubashirkhan** [comment]
even if i load this link inside a webview in my app wheelnav doesn't go to the selected item http://wheelnavjs.softwaretailoring.net/documentation/core.html#sectionProperties

**Comment by softwaretailoring** [comment]
Unfortunately, I don't have experience with React and Webview.
As I know, there is a Meteor package: https://atmospherejs.com/?q=wheelnav
And I've found a Meteor-React issue here: https://forums.meteor.com/t/using-wheelnav-with-a-meteor-react-project/17799
Maybe it helps.
