### ISSUE TITLE
wheelnav js bootstrap modal popup issue

### ISSUE THREAD

**Issue by rajukt** [softwaretailoring/wheelnav#23]
While displaying wheelnav js in bootstrap modal popup ,Main menu items text is not displaying for first time.

**Comment by softwaretailoring** [comment]
Unfortunately I cannot detect the bug but I found a way to achieve your goal. You must use refreshWheel method when open a modal window:

```JS
onclick="mywheelnav.refreshWheel(true);$('#modalPopup').modal();"
```
