### ISSUE TITLE
currentClick

### ISSUE THREAD

**Issue by KentriLuigi** [softwaretailoring/wheelnav#25]
In my pie menu I have 3 choices : 
- FR (by default)
- EN
- IT

I set a function on each item with : 

```javascript
wheelNav.navItems[navItemIndex].navigateFunction = onClick;
 function onClick() {
        alert("The item selected is : " + wheelNav.currentClick) 
 }
```

The problem is that when I click on an item the property  `currentClick` show me the value of my previous click.  It is a bug ? How can I solve this problem ?

**Comment by softwaretailoring** [comment]
You know, it's a feature... :)

The currentClick property will be changed after navigation/animation. The navigateFunction occurs before/under navigation.

You should use animateFinishFunction instead.

```javascript
wheelnav.animateFinishFunction = onClick;
```

Does this solve your problem?

**Comment by KentriLuigi** [comment]
Yes, thank you.
I didn't see this function.

I close this issue ;)
