### ISSUE TITLE
Change dynamically the text of the navTitle

### ISSUE THREAD

**Issue by KentriLuigi** [softwaretailoring/wheelnav#26]
I would like to show the different language available when i select the region. 
For exemple : 

I have two buttons 
    -    EUW (for Europe West) with the choices : French, English, Spanish and Italian
    -    EUE (for Europe East) with the choices : Russian, Chinese, Japanese and Corean

In the same wheelnav i would like to refresh (without recreate a wheelnav) the title with the choices of the clicked button. 

I try something like that : 

```javascript
for (var indexTitle = 0; indexTitle <  radianMenu.navItems.length; indexTitle++) {
       radianMenu.navItems[indexTitle].title = region.choice;
       radianMenu.navItems[indexTitle].titleHover = region.choice;
       radianMenu.navItems[indexTitle].titleSelected = region.choice;
}
```

It works but i think is not the best pratice. 
What do you think about it ?

**Comment by softwaretailoring** [comment]
You're right. There should be a setter method for this case.

And now it is here. :)

```javascript
radianMenu.navItems[indexTitle].setTitle(region.choice);
```

I'm curious about your wheel. It will be available on the web?
