### ISSUE TITLE
How to user wheelnav.js to create sub menu?

### ISSUE THREAD

**Issue by deadliving** [softwaretailoring/wheelnav#27]
Hello,everyone,
       I want to create sub-menu,is there hava some examples or API document?

Thank a lot.

**Comment by softwaretailoring** [comment]
Hi @deadliving 
Basically the sub-menu is two wheelnav on each other.
You can find more information here: http://wheelnavjs.softwaretailoring.net/documentation/core.html#divMultipleWheel

**Comment by wessykes** [comment]
could anyone let me know how to reset the raphael wheel when choosing a slice from the main wheel?
