### ISSUE TITLE
NavItem‘s tooltip doesn't work.

### ISSUE THREAD

**Issue by deadliving** [softwaretailoring/wheelnav#28]
Hi,Gábor Berkesi,
         I also want to use icon with text, but it's not support at present, so I want to use tooltip instead.Follow is the code,is there something error？

       wheelnav.navItems[0].tooltip = "show text";
       wheelnav.refreshWheel();

**Comment by softwaretailoring** [comment]
Hi @deadliving ,
Currently the refresWheel method doesn't refresh tooltips.
You must use initWheel first, then set tooltips, and call createWheel.
Here is a sample: https://github.com/softwaretailoring/wheelnav/blob/v1.6.1/index.html#L114

**Comment by deadliving** [comment]
Hi Gábor Berkesi ,
    Thank you very much.
    Now the tooltip shows correctly.




liuyihui@bigknow.com.cn
 
发件人： Gábor Berkesi
发送时间： 2016-03-29 17:20
收件人： softwaretailoring/wheelnav
抄送： deadliving
主题： Re: [softwaretailoring/wheelnav] NavItem‘s tooltip doesn't work. (#28)
Hi @deadliving ,
Currently the refresWheel method doesn't refresh tooltips.
You must use initWheel first, then set tooltips, and call createWheel.
Here is a sample: https://github.com/softwaretailoring/wheelnav/blob/v1.6.1/index.html#L114
