### ISSUE TITLE
Example submenu 

### ISSUE THREAD

**Issue by ThomBian** [softwaretailoring/wheelnav#29]
On your example page, you show a good example of double wheel nav. but it doesnt work well because all the subemenu is reachable (by click i mean) even the slices hidden. 
Indeed you are only setting the opacity of your svg wich make it fade away but still clickable. I have resolve this on my application by setting the visibility attribute to 'hidden' to all the nav slices (svg object) in my menu programmatically.

**Comment by softwaretailoring** [comment]
@ThomBian Thanks for your feedback!
I modified the submenu example, here I my preferred solution:

```
//Hide submenu
wheel.navItems[0].navItem.hide();
//Show submenu
wheel.navItems[0].navItem.show();
```
