### ISSUE TITLE
Submenu - instructions

### ISSUE THREAD

**Issue by pablodance** [softwaretailoring/wheelnav#30]
Hi - Amazing class - love it -nice one - thogh i cant find any description of how to add a submenu - as per your example?  Is that written up anywhere?

**Comment by softwaretailoring** [comment]
Hi @pablodance 
There is not native function to add a submenu. The submenu in example is two wheelnav on each other.
You can find more information here: http://wheelnavjs.softwaretailoring.net/documentation/core.html#divMultipleWheel
