### ISSUE TITLE
Start wheelnav with no selection

### ISSUE THREAD

**Issue by pablodance** [softwaretailoring/wheelnav#33]
Is it possible to start a wheelnav with nothing selected?

**Comment by softwaretailoring** [comment]
Yes, there is a property for this:

```
cogWheel.selectedNavItemIndex = null;
cogWheel.createWheel();
```

**Comment by ozeone** [comment]
Hi, thanks for a great plugin,
Is there any way to do this with HTML5 data attributes also?
This is my current setup
<div id="divWheel" 
        data-wheelnav 
        data-wheelnav-titlewidth="45" 
        data-wheelnav-titleheight="45"
        data-wheelnav-navitemtitle="test" 
        data-wheelnav-slicepath="CogSlice"
        data-wheelnav-spreaderradius="20"
        data-wheelnav-navangle="180"
        data-wheelnav-slicetransform="RotateTitleTransform"
        data-wheelnav-wheelradius="105">

**Comment by softwaretailoring** [comment]
Hi @ozeone 
You can achieve it with `data-wheelnav-init` attribute, more info [here](http://wheelnavjs.softwaretailoring.net/documentation/html5.html#init).

And then use `wheel.selectedNavItemIndex = null;` before createWheel.

**Comment by johnEvegas** [comment]
Is there a way to trigger selected as null from javascript.  I am using the wheel to open modals and I want to reset the wheel when the modal is closed using some javascript.  I have it working on load just fine but I am using the ring on a pie menu and that still shows, is there a way to have that removed when null?  Thanks in advance for any help!

**Comment by softwaretailoring** [comment]
Hi @johnEvegas 

You can achieve it with the selected property of navItem. The selectedNavItemIndex = null works only at initialization.

```
for (var i = 0; i < myWheelnav.navItems.length; i++) {
    myWheelnav.navItems[i].selected = false;
}
myWheelnav.refreshWheel();
```

**Comment by johnEvegas** [comment]
Thanks!
