### ISSUE TITLE
Where is the complete documentation ?

### ISSUE THREAD

**Issue by RomainFallet** [softwaretailoring/wheelnav#34]
I can't find what I need on the documentation here : http://wheelnavjs.softwaretailoring.net/documentation/.

Where is the complete list of all functions and parameters available ? For example, I want to manage the size of the inner gap of a donut wheelnav, but I can't see anything about that.

There are also multiple examples here http://wheelnavjs.softwaretailoring.net/examples.html but no code to reproduce them.

What did I miss ? Thanks for the help.

**Comment by softwaretailoring** [comment]
You can find more information about your current question here: http://wheelnavjs.softwaretailoring.net/documentation/slicePath.html#customization There are customizable variables for DonutSlice: minRadiusPercent, maxRadiusPercent https://github.com/softwaretailoring/wheelnav/blob/v1.6.1/js/source/slicePath/wheelnav.slicePath.Donut.js

Unfortunately the reference of functions and parameters doesn't exist. I know this lack of documentation and I would like to create one.

Thanks for your feedback!

**Comment by jodybrabec** [comment]
You are a true software engineer, who is willing to say "I know this lack of documentation and I would like to create one".  Oh if only there were more developers out there like you!  Thanks for your great software and honesty!
