### ISSUE TITLE
wheelnav slice angle

### ISSUE THREAD

**Issue by ansari007** [softwaretailoring/wheelnav#35]
Hello hope everything is good , i was wondering if i could make slices with different  angles or sizes in wheelnav like a pie chart

**Comment by softwaretailoring** [comment]
Hi @ansari007 
You can use sliceAngle property of navItem.
Here is a [demo](http://wheelnavjs.softwaretailoring.net/inspirations/tibet.html) and here is the source [code](https://github.com/softwaretailoring/wheelnav.inspirations/blob/master/tibet.html#L49).

**Comment by ansari007** [comment]
Thanks @softwaretailoring  that was what i need :) ,
another thing if i put a image in the slice is there a way to make the image size fit in the slice 
(in case if the slice is to small ex: slice angle=25)
thx for everything :)

**Comment by softwaretailoring** [comment]
Do you mean use an image as a navTitle?
There is a titleHeight and titleWidth property of navItem. [Documentation](http://wheelnavjs.softwaretailoring.net/documentation/html5.html#navitem)

**Comment by ansari007** [comment]
Thank you :) @softwaretailoring
