### ISSUE TITLE
Gradients slice color

### ISSUE THREAD

**Issue by ansari007** [softwaretailoring/wheelnav#37]
Hello,i was wondering if i can apply gradients color to the slices

**Comment by softwaretailoring** [comment]
You can use gradients via JavaScript with following format: "angle-startcolor-endcolor".
Here is a sample (the third one): http://wheelnavjs.softwaretailoring.net/test
Here is a source code: https://github.com/softwaretailoring/wheelnav/blob/v1.6.1/index.html#L71
(Sorry for late response, I was on holidays.)
