### ISSUE TITLE
Destroy WheelNav

### ISSUE THREAD

**Issue by ifedapoolarewaju** [softwaretailoring/wheelnav#38]
As there is a method `createWheel`, might come in handy to have a `destroyWheel` method as well

**Comment by softwaretailoring** [comment]
Hi @ifedapoolarewaju 

What is the main reason of your query?

This method removes wheelnav from DOM: 
`myWheelnav.raphael.remove();`

Or do you want more?

**Comment by ifedapoolarewaju** [comment]
@softwaretailoring `myWheelnav.raphael.remove();` is sufficient. I later found that out. We can close this if no one else is concerned.

**Comment by softwaretailoring** [comment]
OK
