### ISSUE TITLE
Drop ID requirement

### ISSUE THREAD

**Issue by LordZardeck** [softwaretailoring/wheelnav#39]
I really want to use this library, but it seems that you can't use this library without an ID attribute. I can't use an ID, which makes it impossible to use this library. Unless there is an undocumented method of do so. What i'd like to see is the option of passing in the element itself.

**Comment by softwaretailoring** [comment]
The ID attribute of a holder div is a fundamental part of current codebase. For example when you have two wheelnavs on same page then they own unique CSS class names which constructed based on the ID of holder div.
I think you have some kind of identifier (name, class), so I've created a [CodePen sample](http://codepen.io/softwaretailoring/pen/LbmPEO/) with a wrapper function which may satisfy your requirements.
Is it a possible solution for you?

**Comment by softwaretailoring** [comment]
Hi @LordZardeck 
Can you test the above sample? May I close this issue?
