### ISSUE TITLE
Arc text - Pie Menu / Radial Menu

### ISSUE THREAD

**Issue by huascar** [softwaretailoring/wheelnav#4]
"Arc tex", is very useful and would be interesting to include this option for the text displayed in the menu foot or round buttons show an arched text.

**Comment by solverat** [comment]
:thumbsup:

**Comment by alexandre-pereira** [comment]
Could we, please, have any news about this ?

**Comment by softwaretailoring** [comment]
@alexandre-pereira I found a possible implementation, but currently it isn't in my todo list.

Here is a demo: http://jsbin.com/UJIYAco/1/edit?html,js,output

May be a contribution?

**Comment by alexandre-pereira** [comment]
I'll try to implement it ;)

**Comment by softwaretailoring** [comment]
Great news! :) Feel free to contact me when you have a question.

**Comment by Sibinraj** [comment]
@softwaretailoring
Hi, Can you able to help me to sort out this issue?
https://stackoverflow.com/questions/55243617/wheelnav-menu-click-not-working-when-using-curvetext-functionality
