### ISSUE TITLE
render issues

### ISSUE THREAD

**Issue by ansari007** [softwaretailoring/wheelnav#40]
hey hope your'e doing well, i have 5 items in my wheelnav and i'm giving to each one of them slice angle it's working fine however when i give to a slice an angle bigger than 180 the rendering of wheelnav goes wrong.

**Comment by softwaretailoring** [comment]
Hi @ansari007 
Thanks for your feedback!
What types of slicePath did you use? Did you set navItemsContinuous to true? Can you give me a sample code?

**Comment by ansari007** [comment]
Hey there's the code i'm using:
wheel = new wheelnav("wheelDiv");

wheel.slicePathFunction = slicePath().DonutSlice;
wheel.initWheel(["init","sas","dsadas","ad","dsd"]);
wheel.navItems[0].sliceAngle =210;
wheel.navItems[1].sliceAngle =45;
wheel.navItems[2].sliceAngle =45;
wheel.navItems[3].sliceAngle =30;
wheel.navItems[4].sliceAngle =30;
wheel.navItemsContinuous = true;
 
wheel.createWheel();

result:
![errorrender](https://cloud.githubusercontent.com/assets/11501271/21173155/0eef0578-c1df-11e6-90ac-87b882191b39.png)

if the value is lower than 180 it's working fine.

Thanks.

**Comment by softwaretailoring** [comment]
This bug affected Donut, OuterStroke, Pie, Tutorial, Wheel, YinYang slicePaths. I fixed them now.
