### ISSUE TITLE
PieSlice can't move single slice and replicate documentation example

### ISSUE THREAD

**Issue by bachras** [softwaretailoring/wheelnav#41]
Thank you for great plugin. I can't replicate example from http://wheelnavjs.softwaretailoring.net/documentation/sliceTransform.html .I would like to move single selected slice. Could you assist me with this? Thanks in advance.

**Comment by softwaretailoring** [comment]
Hi @bachras 
Did you try this?

`wheel.sliceSelectedTransformFunction = sliceTransform().MoveMiddleTransform;`

Thanks for your feedback, I've added a link to http://wheelnavjs.softwaretailoring.net/documentation/sliceTransform.html

**Comment by bachras** [comment]
Thank you for prompt reply. I have tried sliceTransformFunction, but not sliceSelectedTransformFunction. 
It worked like a charm.
