### ISSUE TITLE
Dynamically select the slice

### ISSUE THREAD

**Issue by bachras** [softwaretailoring/wheelnav#42]
I am having a problem trying to select the slice dynamiclally via button. I wonder if this is possible and if yes how to implement it? Any help will be highly appreciated. Thanks

**Comment by softwaretailoring** [comment]
Did you find this?
http://wheelnavjs.softwaretailoring.net/documentation/core.html
In 'Methods' section press 'navigate' button to code snippet.

**Comment by bachras** [comment]
Thank you very much, somehow I missed that part.
