### ISSUE TITLE
slicePathAttr of stroke messes with hover values

### ISSUE THREAD

**Issue by ponentesincausa** [softwaretailoring/wheelnav#43]
So if I set a slicePathAttr of stroke, and hover over the slices their colour stays as if they where hovered until I click on them. 

This is my code. 

```    wheel.slicePathFunction = slicePath().DonutSlice;
    wheel.wheelRadius = 200;
    wheel.spreaderEnable = true;
    wheel.spreaderRadius = 35;
    wheel.navAngle = 270;
    wheel.colors = colorpalette.purple;
    wheel.slicePathAttr = { stroke: '#fff', 'stroke-width': 6 };

    wheel.createWheel(firstElements);
    wheel.navigateWheel(0);
```

I recorded a GIF to demonstrate. 
 
![wheel](https://cloud.githubusercontent.com/assets/8941178/23138980/de90e132-f76f-11e6-8ebf-f7602502ecd8.gif)

btw thanks for this awesome library.

**Comment by softwaretailoring** [comment]
Hi @ponentesincausa 

Please set the sliceHoverAttr and sliceSelectedAttr also.

Or use css for styling: http://wheelnavjs.softwaretailoring.net/documentation/css3.html

I hope it helps!

**Comment by ponentesincausa** [comment]
Hello! I added both, but still hovering-off will not return to the original color. Am I missing something? I wanted to leave css mode as a last resort as I am adding colors using an array to make a gradient.

```window.onload = function () {
    var wheel = new wheelnav("wheelDiv");

    wheel.slicePathFunction = slicePath().DonutSlice;
    wheel.wheelRadius = 200;
    wheel.spreaderEnable = true;
    wheel.spreaderRadius = 65;
    wheel.spreaderTitleFont = '100 60px Roboto'
    wheel.navAngle = 270;
    wheel.titleRotateAngle = 90;
    wheel.colors = colorpalettecustom.bluepurple;
    wheel.slicePathAttr = { stroke: '#fff', 'stroke-width': 2 };
    wheel.sliceHoverAttr = { stroke: '#fff', 'stroke-width': 2, 'fill': 'green'};
    wheel.sliceSelectedAttr = { stroke: '#fff', 'stroke-width': 2, 'fill': 'blue'};

    wheel.createWheel(firstElements);
    wheel.navigateWheel(0);```

(green stays selected after hover off)
![image](https://cloud.githubusercontent.com/assets/8941178/23294666/245fbf48-fa32-11e6-9ed5-b25fe58f5024.png)

**Comment by softwaretailoring** [comment]
One more step: you must use fill value in slicePathAttr also.
And a suggestion: use these properties before createWheel.
Here is a JS Bin for demo: http://jsbin.com/hurofo/edit?html,js,output

**Comment by ponentesincausa** [comment]
Tried it and worked! so instead of defining the color through an array within the colors function it's defined here. I've got wheels with 30 paths, this is gonna be fun XD. 

Thank you for replying, I will close the issue now. :)
