### ISSUE TITLE
Marker Animation

### ISSUE THREAD

**Issue by mat-mcloughlin** [softwaretailoring/wheelnav#44]
Is there anyway to remove the animation of the PieLineMarker marker?

**Comment by softwaretailoring** [comment]
What kind of animation do you think?

`wheel.clickModeRotate = false;` -> the marker moves around the wheel
`wheel.clickModeRotate = true;` -> the marker remains on its original position

**Comment by mat-mcloughlin** [comment]
I'm referring to the marker that moves around the outside. See this example

https://jsfiddle.net/1nynwv4k/1/

btw, nice little lib, appreciate the work on it

**Comment by softwaretailoring** [comment]
Thanks!
Finally, I understand. :)
You should use `myWheelnav.animatetime = 0;` for this purpose.
Here is your modified example: https://jsfiddle.net/4qka7xc6/1/

**Comment by softwaretailoring** [comment]
Or you can use `myWheelnav.marker.animatetime = 0;` after createWheel and before refreshWheel.
The other animations remain in this case.
Here is another example with it: https://jsfiddle.net/4qka7xc6/2/

**Comment by mat-mcloughlin** [comment]
Thats perfect!

Cheers man
