### ISSUE TITLE
Disable menu items

### ISSUE THREAD

**Issue by mat-mcloughlin** [softwaretailoring/wheelnav#45]
Is it possible to disable a given menu item dynamically?

**Comment by softwaretailoring** [comment]
Only before createWheel.

```
  wheel = new wheelnav("wheelDiv");
  wheel.initWheel(["1","2","3","4","5","6"]);
  wheel.navItems[1].enabled = false;
  wheel.createWheel();
```

Here is a [JS Bin for demo](http://jsbin.com/ledaza/edit?js,output)

**Comment by mat-mcloughlin** [comment]
works a treat.. mind if I ask you had to select a different menu item on startup too?

**Comment by softwaretailoring** [comment]
You can do this with navigateWheel() function.

`wheel.navigateWheel(2);`

I've modified the above bin for this.

**Comment by softwaretailoring** [comment]
@mat-mcloughlin may I close this issue?

**Comment by mat-mcloughlin** [comment]
You may, thanks for your help

One other problem I came across was when selecting the start position for the wheel it fires the onclick event which caused me problems. Worked around it easy enough but don't know if there is a way to do it without?

**Comment by mat-mcloughlin** [comment]
You may, thanks for your help

One other problem I came across was when selecting the start position for the wheel it fires the onclick event which caused me problems. Worked around it easy enough but don't know if there is a way to do it without?

**Comment by softwaretailoring** [comment]
Sorry, I don't understand exactly.
Can you give me a jsfiddle about this?
