### ISSUE TITLE
Ability to not-animate titles on startup, when titleRotateAngle is set to something other than default

### ISSUE THREAD

**Issue by ponentesincausa** [softwaretailoring/wheelnav#46]
Hello! So I set the titleRotateAngle to 90. Is there a feature to cancel the animation that bounces the titles until their final position?

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/8941178/23806409/2c366478-0587-11e7-876e-f8275045d88a.gif)

**Comment by softwaretailoring** [comment]
Yes, there is a property for that.

`wheel.initTitleRotate = true;`

May I use this site in [World wide wheel](http://wheelnavjs.softwaretailoring.net/spinit.html#worldwidewheel) section? :smile:

**Comment by ponentesincausa** [comment]
That'd be awsome! I will deploy to github in upcoming days and let you know. 

Thanks for the `wheel.initTitleRotate = true;` it worked perfectly. I'll close the issue.
