### ISSUE TITLE
How to Add Background to Spreader?

### ISSUE THREAD

**Issue by lenichols** [softwaretailoring/wheelnav#48]
I dont see anywhere in the docs that mention how to add a custom background to Spreader? 

Also, whats the best method to allow multi-line text on nav items and also spreader text?

**Comment by softwaretailoring** [comment]
Did you check this? 
http://wheelnavjs.softwaretailoring.net/documentation/spreader.html
Under Spreader basics press 'attrs' button.

You can customize background via CSS also: http://wheelnavjs.softwaretailoring.net/documentation/css3.html#spreader

You can place multi-line text with '\n' escape character.

**Comment by lenichols** [comment]
ive looked at these pages in the docs but they are very basic. Not mentioning how to make the title multi-line or manipulate a js rendered wheel.

my wheel:

![screen shot 2017-04-11 at 4 06 28 pm](https://cloud.githubusercontent.com/assets/5247113/24934543/005d17bc-1ed1-11e7-80a7-9992d8d4f536.png)


and the styling...

![screen shot 2017-04-11 at 4 07 00 pm](https://cloud.githubusercontent.com/assets/5247113/24934547/0f51edce-1ed1-11e7-8bdc-ffd6935ae64c.png)

How do you change css on a javascript rendered wheel using js api? My titles are rendered from the server. i cant place a \n in the response data. Any ideas?

**Comment by softwaretailoring** [comment]
You can handle styling via JavaScript OR CSS.
JavaScript styling here: http://wheelnavjs.softwaretailoring.net/documentation/navItem.html#divAttributesWheel

About \n. Can't you modify the server code? I think multiline possible only with \n.

About gradient. Please check the following sample: https://github.com/softwaretailoring/wheelnav/blob/v1.7.0/index.html#L72
