### ISSUE TITLE
Spreader MouseDown Event

### ISSUE THREAD

**Issue by lenichols** [softwaretailoring/wheelnav#49]
I see no where in the documentation does it show how to evoke a mousedown or click function on spreader. 

This project is pretty awesome but the lack of documentation decreases its possibilities which I am sure once i figure out how to customize it, it will be fine.

**Comment by softwaretailoring** [comment]
Yes. I know, I know, I know the lack of the more detailed documentation!
By the way, you can get free support here!
Okay, the moaning is over... :)
Anyway, thanks for the feedback. I would like to create a better documentation, but currently I don't have enough time for it.

Unfortunately the spreader click function isn't customizable currently out of the box.
You must modify source code here:
https://github.com/softwaretailoring/wheelnav/blob/v1.7.0/js/source/spreader/wheelnav.spreader.core.js#L45
and here:
https://github.com/softwaretailoring/wheelnav/blob/v1.7.0/js/source/spreader/wheelnav.spreader.core.js#L114

**Comment by softwaretailoring** [comment]
I found a workaround for your issue.
Please check this [JS Bin](http://jsbin.com/sarosoh/edit?html,js,output)

**Comment by softwaretailoring** [comment]
Hi @lenichols ,
May I close this issue?
