### ISSUE TITLE
Changing In/Out Title and Angular2

### ISSUE THREAD

**Issue by MingC0re** [softwaretailoring/wheelnav#50]
Hi,  

I have an application where I need to modify the In/Out Title and have it update.  What is the proper way of changing and having it take affect?  I tried the following but it doesn't seem to change.

```
this.wheelnav.spreaderInTitle = 'new TITLE';
this.wheelnav.refreshWheel();
```

Could you provide an example of how to setup a MenuSliceWithoutLine on the left/right corner so it only uses a total of 90 degrees of the screen instead of 360?

Is there a way to long press and short press feature?

Will you be porting this to Angular2 or 4?

Thanks in advance.

**Comment by MingC0re** [comment]
For MenuSliceWithoutLine is there a way to modify the size of the circle for the navItem?  I tried titleRadius but it doesn't seem to do anything.  

Not sure if I'm doing something wrong, but when I subscribe for the mouseover event, it doesn't seem to always fire.  It almost seems like unless the text is clicked perfectly its not fired.

**Comment by MingC0re** [comment]
I notice the following Error when calling removeWheel().  Is there a specific setting or order for executing the command?

> raphael.min.js:2 Error: <tspan> attribute dy: Expected length, "NaN".
n	@	raphael.min.js:2
ot	@	raphael.min.js:2
g	@	raphael.min.js:2
r.attr	@	raphael.min.js:2
or	@	raphael.min.js:2
ZoneDelegate.invokeTask	@	zone.js:365
onInvokeTask	@	core.umd.js:9236
ZoneDelegate.invokeTask	@	zone.js:364
Zone.runTask	@	zone.js:265
ZoneTask.invoke	@	zone.js:432

**Comment by softwaretailoring** [comment]
Spreader sample:

```
  wheel.spreader.inTitle.title = '1';
  wheel.spreader.outTitle.title = '2';
  wheel.refreshWheel();
```
MenuSliceWithoutLine sample:

```
  wheel.slicePathFunction = slicePath().MenuSliceWithoutLine;
  wheel.slicePathCustom = new MenuSliceCustomization();
  wheel.slicePathCustom.menuRadius = 40;
  wheel.sliceSelectedPathCustom = new MenuSliceCustomization();
  wheel.sliceSelectedPathCustom.menuRadius = 40;

  wheel.navItemsContinuous = true;
  wheel.sliceAngle = 45;
  wheel.navAngle = -90;
  wheel.clickModeRotate = false;

```
More custom property of menuslice can be found [here](https://github.com/softwaretailoring/wheelnav/blob/v1.7.0/js/source/slicePath/wheelnav.slicePath.Menu.js)

Here is a [JS Bin](http://jsbin.com/ciyigo/edit?html,js,output) with above samples.

Currently there is no way for long press and short press.
I didn't plan to port it to Angular2, but I'll provide help if you think so. ;)

The remoteWheel must be call after createWheel. Please send me a sample with source if problem still exist.
