### ISSUE TITLE
Advanced constructor - Click navItems simultaneously

### ISSUE THREAD

**Issue by leemel2016** [softwaretailoring/wheelnav#51]
I created a multiple wheelnav using the Advanced constructor with a slicePath().DonutSlice and my aim is to click either the image or the text slice and they will be selected simultaneously, like the cogSlice.

I tried using this code, 

```
newheels0.navItems[0].navigateFunction = function() {
	newheels1.navigateWheel( 0 );
};
newheels1.navItems[0].navigateFunction = function() {
	newheels0.navigateWheel( 0 );
};
```
then click the other navItem, whenever I click the navItem[0] to test it, my browser stuck up, and i tried to wait it, and it occurs an error "Maximum call stack size exceeded". I think this returns an infinite loop?

What do you think is the problem here? :) Thank you.

**Comment by softwaretailoring** [comment]
Please try this:

```
this.newheels0 = new wheelnav("newheel0");
this.newheels1 = new wheelnav("newheels1", this.newheels0.raphael);

thisnewheels0 = this.newheels0;
thisnewheels1 = this.newheels1;
this.newheels0.navItems[0].navigateFunction = function () {
    thisnewheels1.navigateWheel(0);
}
this.newheels1.navItems[0].navigateFunction = function () {
    thisnewheels0.navigateWheel(0);
}
```

**Comment by leemel2016** [comment]
Thank you for the quick reply. 

Unfornately, it still not working :(

Here's my sample code:

```
window.onload = function () {

   setWheel();
              
};// on load


var setWheel = function(){
    this.newheels0 = new wheelnav("newheel0", null, 300, 300);
    this.newheels1 = new wheelnav("newheel1", this.newheels0.raphael);

    this.newheels0.slicePathFunction = slicePath().DonutSlice;
    this.newheels0.slicePathCustom = slicePath().DonutSliceCustomization();
    this.newheels0.sliceSelectedPathCustom = this.newheels0.slicePathCustom;
    this.newheels0.sliceInitPathCustom = this.newheels0.slicePathCustom;
    this.newheels0.slicePathCustom.minRadiusPercent = 0.5;
    this.newheels0.slicePathCustom.maxRadiusPercent = 0.7;

    this.newheels1.slicePathFunction = slicePath().DonutSlice;
    this.newheels1.slicePathCustom = slicePath().DonutSliceCustomization();
    this.newheels1.sliceSelectedPathCustom = this.newheels1.slicePathCustom;
    this.newheels1.sliceInitPathCustom = this.newheels1.slicePathCustom;
    this.newheels1.slicePathCustom.minRadiusPercent = 0.1;
    this.newheels1.slicePathCustom.maxRadiusPercent = 0.5;

    thisnewheels0.createWheel(["1","2","3","4"]);
    thisnewheels1.createWheel(["a","b","c","d"]);

    thisnewheels0 = this.newheels0;
    thisnewheels1 = this.newheels1;

    this.newheels0.navItems[0].navigateFunction = function () {
        thisnewheels1.navigateWheel(0);
    }
    this.newheels1.navItems[0].navigateFunction = function () {
        thisnewheels0.navigateWheel(0);
    }
}
```
My browser still stuck whenever i click the `navItems[0]`

**Comment by softwaretailoring** [comment]
Your above code contains an error.
You used `thisnewheels0` before createWheel instead of `this.newheels0`.
I've created a [JS Bin](http://jsbin.com/rivuruf/edit?html,js,output) and it works well.

**Comment by Mhj520** [comment]
There are no examples of submenu？Can you give me a guide demo?

**Comment by softwaretailoring** [comment]
Did you check the JS Bink link in my comment above?
I think this is a good example of submenu.

**Comment by Mhj520** [comment]
![20170503102022](https://cloud.githubusercontent.com/assets/28295657/25646735/cab0786a-2fed-11e7-9866-b496886bf474.png)
There is no such example as the official website?thx

**Comment by leemel2016** [comment]
Sorry for the late reply I just came back from my vacation. It works great when i use your cdn  
 - http://cdn.jsdelivr.net/wheelnav/1.7.0/wheelnav.min.js

But if I use the local wheelnav.min.js with the same version 1.7.0, it still stuck in the browser, I don't know why. Anyway, I'll just used the CDN. Thank you very much. 

One last question, is it possible to populate the .navigateFunction via FOR loop?

```
for( var i = 0; i < 4; i++){
	thisnewheels0.navItems[i].navigateFunction = function() {
		newheels1.navigateWheel( i )
	};
}
```
My aim is to make the wheel navItem dynamic.

**Comment by softwaretailoring** [comment]
@Mhj520 There is no such example. Please check [this](https://github.com/softwaretailoring/wheelnav/issues/31) issue.

**Comment by softwaretailoring** [comment]
@leemel2016 Yes, you can populate it in this way.

**Comment by Mhj520** [comment]
thank you!!!
