### ISSUE TITLE
Is there a variable that indicates whether the spreader is on or off?

### ISSUE THREAD

**Issue by ponentesincausa** [softwaretailoring/wheelnav#52]
Is there a variable that indicates whether the spreader is on or off? preferably that throws a boolean. The way currentClick indicates the number in the array that is currently selected.

**Comment by ponentesincausa** [comment]
Thank you. You are awesome. I applied it and uploaded a repo with examples included. [Find it here](https://github.com/ponentesincausa/idea-roulette/blob/master/README.md)

**Comment by softwaretailoring** [comment]
You're welcome. Thanks for the link of your repo!
