### ISSUE TITLE
1 Item in Array Breaks the Wheel

### ISSUE THREAD

**Issue by lenichols** [softwaretailoring/wheelnav#53]
If i have two or more names in my array, the wheel loads createWheel(["one","two"])

If there is only 1 result in my object call createWheel(["one"]) the wheel only loads the titles... the slices dont show up. Please help

**Comment by softwaretailoring** [comment]
What kind of slicePath do you use?
I've checked it with PieSlice and DonutSlice and these work well.

**Comment by lenichols** [comment]
DonutSlice with Spreader... @softwaretailoring

**Comment by softwaretailoring** [comment]
I've tested the following code and it works well:

```
var DonutSlice = new wheelnav("DonutSlice");
DonutSlice.slicePathFunction = slicePath().DonutSlice;
DonutSlice.spreaderEnable = true;
DonutSlice.createWheel(["one"]);
```

Please create a JS Bin or JSFiddle with your issue or send me the url of your site where I can check your issue.

**Comment by gunmiosb** [comment]
I've created a JSFiddle with the issue: [JSFiddle](https://jsfiddle.net/gm5pfngu/2/). 

The percent parameter in the slice path function is very small for one value.

**Comment by softwaretailoring** [comment]
Hi @gunmiosb 

Thank you for JSFiddle! The above code worked with current repository, but the affected parts were not released.

It was a time for a new release: [v1.7.1](https://github.com/softwaretailoring/wheelnav/releases/tag/v1.7.1)

Please change your link to this: https://cdn.jsdelivr.net/npm/wheelnav@1.7.1/js/dist/wheelnav.min.js

Here is a modified version of your [JSFiddle](https://jsfiddle.net/gm5pfngu/3/)
