### ISSUE TITLE
Trigger the spreader 

### ISSUE THREAD

**Issue by DylanCa** [softwaretailoring/wheelnav#54]
Hey dude ! Really nice work you've done here, that helps a lot and that's really beautiful and well coded. I just have a question, I tried to find a proper way to trigger the spreader in order to close the wheelnav without clicking in the middle, but can't manage to find a way. Can you help me there ?

Thank you in advance !

**Comment by softwaretailoring** [comment]
Hi @DylanCa  
Thanks for your kindly feedback! 👍 
You can use [wheel.spreadWheel()](https://github.com/softwaretailoring/wheelnav/blob/v1.7.0/js/dist/wheelnav.js#L460) function for that.

**Comment by DylanCa** [comment]
God .. I swear to god I've tried so many methods without success, even went looking onto the object and ended with a "wheel.spread.spreader.spreadHelped.spreadWheel()" method .. Shame on me haha

Thank you a lot ! And what a fast answer ! :D You a pro, definitely !
