### ISSUE TITLE
Multiple wheelnavs 

### ISSUE THREAD

**Issue by Mambix** [softwaretailoring/wheelnav#55]
Is it possible to have one template for wheelnav but that can be called from different locations in your HTML code. I also need it's buttons to call same JS functions but with different parameters based on the location clicked.

is that possible?

**Comment by softwaretailoring** [comment]
Hi @Mambix 
Please describe your issue on another way, I don't understand exactly what do you want. What is a 'template'? And what kind of parameters do you think?

**Comment by Mambix** [comment]
I made my own lib for this. Fount out I can not manipulate elements the way I wanted
