### ISSUE TITLE
How to import wheelnav?

### ISSUE THREAD

**Issue by HorseBinky** [softwaretailoring/wheelnav#56]
Greetings!
I try to implement a simple example of wheelnav in my js application, but struggling on the first steps.
I installed wheelnav with npm.
My class looks something like:
```javascript
import {wheelnav} from 'wheelnav'

export class RadialMenu {
	wheel: wheelnav
	menuContainer: HTMLElement
	
	constructor() {
		this.wheel = new wheelnav('wheelDiv');
		this.wheel.clockwise = false;
		this.wheel.createWheel(['title-0', 'title-1', 'title-2', 'title-3', 'title-4']);
		this.menuContainer = document.createElement('div')
		this.menuContainer.appendChild(this.wheel)
	}
}
```
So, when I want to use this class I constantly got the following error message:
Uncaught TypeError: wheelnav_1.default is not a constructor

I am really thankfull for any suggestions!

**Comment by softwaretailoring** [comment]
Hi @HorseBinky 
Can you put your issue to a JSFiddle or JSBin? It would be helpful.
However, the appendChild method cannot work in this way because wheelnav's constructor doesn't return as a DOM node.
Furthermore I think your menuContainer variable should be equivalent the "wheelDiv".

**Comment by davidebarros** [comment]
@HorseBinky  seems like you will need a global import 
`import 'wheelnav'` 
are you using react?
