### ISSUE TITLE
Image as Spreader Background ?

### ISSUE THREAD

**Issue by DylanCa** [softwaretailoring/wheelnav#57]
Hi,

I was wondering if I can put a custom image as the Spreader, and if I can modify it later using JS ? I know I can put an icon instead of the SpreaderTitle, but I need an image there actually.

Thank you !

**Comment by softwaretailoring** [comment]
You can find a sample for this in [index.html](https://github.com/softwaretailoring/wheelnav/blob/v1.7.0/index.html#L37) of this repo.

**Comment by DylanCa** [comment]
Awesome ! And about dynamically modifying the spreaderTitle image ? I assume I have to reassign the wheel.spreaderInTitle / .spreaderOutTitle, but I can't find a way to "refresh" the wheel in order to display the new image .. Got an Idea ?

**Comment by elvis7449** [comment]
Mind telling what you did? :p

**Comment by softwaretailoring** [comment]
`wheel.spreader.inTitle.src = "icon.png";`
