### ISSUE TITLE
How to unselect whenever I click the spreader ?

### ISSUE THREAD

**Issue by DylanCa** [softwaretailoring/wheelnav#58]
Hi, it's me again, I love your work.

I use your wheel as a category menu, and I need it to unselect the different category whenever the spreader is clicked, this way when I hover the last category selected, it'll display as if I never clicked on it. I don't know if I'm understandable haha

Thank you once again !

**Comment by softwaretailoring** [comment]
You guessed right, I don't understand exactly. :)

Maybe do you need multiselect? There is a [property](https://github.com/softwaretailoring/wheelnav/blob/v1.7.0/js/dist/wheelnav.js#L93) for that.

**Comment by DylanCa** [comment]
Dang, sorry :/ I'll try to explain it better.

When you set your wheel for the first time, there's nothing selected nor hovered, right ? Every slice just stands there waiting for the user to do something, and when the user clicks on one slice, it gets bigger ( for example ). 

What I want to do is, when the user clicks on the spreader, the wheel "resets" itself, just as if it has just been created. So, no slice selected, nothing at all.

Maybe it is clearer ? Take a look at this site ( still in alpha tho ), you'll understand : www.danielsicard.fr . When you click on a category, the wheel disapears. Click on the bottom arrow, and then try to hover the same category you just clicked on. Nothing happens, the pointer doesn't even change.

I'd like to reset it when the spreader is clicked !

**Comment by softwaretailoring** [comment]
Oookay, I've got it finally! :)

You can use the `selected` property of navitems.

```
  for (i = 0; i < wheel.navItemCount; i++) {
    wheel.navItems[i].selected = false;
  }
  wheel.refreshWheel();
```

**Comment by DylanCa** [comment]
Thank you kind sir, that worked !
