### ISSUE TITLE
Directive AngularJS for use WheelnavJS

### ISSUE THREAD

**Issue by huascar** [softwaretailoring/wheelnav#6]
It would be an interesting idea if you use AngularJS, and you can create one directive, to use your library. It would be great!

**Comment by ivicodin** [comment]
any avance on this?

WheelnavJS rules by the way!

**Comment by softwaretailoring** [comment]
Thanks for your feedback!
Unfortunately I don't have enough resources for it. I think an AngularJS directive would be great, but I'll implement some core features at first.
However, it's an open source project, so contributors are welcome! :)

**Comment by sinanspd** [comment]
If we had https://github.com/softwaretailoring/wheelnav/issues/90 
I would be happy to put together a directive or at least write a tutorial to get this to properly work with Angular. It's still fairly easy to get this to work with angular but without being able to receive any output it would simply be visual sugar and couldn't actually alter the component state etc.

**Comment by softwaretailoring** [comment]
@sinanspd , it would be great! :)
