### ISSUE TITLE
Feature request... have no menu item selected during init

### ISSUE THREAD

**Issue by toddtigerpop** [softwaretailoring/wheelnav#61]
Hello,

Is it possible to set no menu items selected during init?  For instance, navigateWheel(-1) de-selects all the menu items as I'd like, but I get a "Cannot read property 'navAngle' of undefined" error.

Thanks.

**Comment by softwaretailoring** [comment]
Yes, there is a property for this:

```
wheel.selectedNavItemIndex = null;
wheel.createWheel();
```

[Other issue](https://github.com/softwaretailoring/wheelnav/issues/33) about it.

**Comment by toddtigerpop** [comment]
Works great, thanks!  Great work on this menu!
