### ISSUE TITLE
Deformation on DonutSlice Chrome

### ISSUE THREAD

**Issue by Zyostes** [softwaretailoring/wheelnav#62]
I am using version 1.7.0 of wheelnav, i have that parameters : 
```
wheel = new wheelnav("wheelnav");
wheel.colors = ['#3299BB'];
wheel.slicePathFunction = slicePath().DonutSlice;
wheel.markerEnable = true;
wheel.slicePathAttr = {'fill': '#3299BB', 'fill-opacity': 1, 'stroke': '#f1f2f2', 'stroke-width': 20};
wheel.sliceSelectedAttr = {'fill': '#093F4C'};
```
In Chrome (Version 59.0.3071.115 (Build officiel) (64 bits)), Windows 10, i have this deformation : 

![apsys business partner integrateur de solutions de gestion pme pmi](https://user-images.githubusercontent.com/5689105/28363166-c0bca738-6c7f-11e7-9bc1-51e5306d4381.png)

In Mozilla Firefox i have not this bug.

Thank you per advance.

**Comment by softwaretailoring** [comment]
Hi @Zyostes 
Sorry for late response, I was on holiday.
I have similar environment than yours, but I cannot reproduce your issue.
Can you make a JSBin or JSFiddle about it?

**Comment by softwaretailoring** [comment]
Hi @Zyostes 
Do you still have this issue?
