### ISSUE TITLE
Wrong slice selection in IOS safari

### ISSUE THREAD

**Issue by elvis7449** [softwaretailoring/wheelnav#63]
All other browsers are working fine with my code. Only in ios safari i have problems with the selection. When I clicked on a slice it wasn't always jumping to the one I selected. It selects some other slice. Any idea whats happening? And how to i center wheelnav to any screen resolution?

![capture](https://user-images.githubusercontent.com/31389395/29752136-cb37e2d4-8b71-11e7-9d48-f77c8a0e5ec6.PNG)

**Comment by softwaretailoring** [comment]
Hi @elvis7449 
Please add your source code for investigation.
A JSBin or JSFiddle would be the best.

**Comment by elvis7449** [comment]
Possible to email? Give me your email ID

**Comment by elvis7449** [comment]
<code>
$( document ).ready(function() {
   $("#loading").css("display", "none");

wheel1 = new wheelnav('wheelDiv');
wheel2 = new wheelnav('wheel2', wheel1.raphael);

wheel1.spreaderEnable = true;
wheel1.spreaderInPercent = 2.0;
wheel1.spreaderOutPercent = 2.0;
wheel1.spreaderInTitle = 'B3-CR3';
wheel1.spreaderOutTitle = 'B3-CR3';
wheel1.spreaderTitleFont = 'bold 16px Helvetica';
wheel1.spreaderPathInAttr = { fill: '#fff', 'stroke-width': 0.5, stroke: '#f15625' };
wheel1.spreaderPathOutAttr = { fill: '#fff', 'stroke-width': 0.5, stroke: '#f15625' };
wheel1.spreaderTitleInAttr = { fill: '#f15625' };
wheel1.spreaderTitleOutAttr = { fill: '#f15625' };

wheel1.slicePathFunction = slicePath().DonutSlice;
wheel1.slicePathCustom = slicePath().DonutSliceCustomization();
wheel1.slicePathCustom.minRadiusPercent = 0.23;
wheel1.slicePathCustom.maxRadiusPercent = 0.9;
wheel1.sliceSelectedPathCustom = wheel1.slicePathCustom;
wheel1.sliceInitPathCustom = wheel1.slicePathCustom;

wheel2.slicePathFunction = slicePath().DonutSlice;
wheel2.slicePathCustom = slicePath().DonutSliceCustomization();
wheel2.slicePathCustom.minRadiusPercent = 0.9;
wheel2.slicePathCustom.maxRadiusPercent = 1.0;
wheel2.sliceSelectedPathCustom = wheel2.slicePathCustom;
wheel2.sliceInitPathCustom = wheel2.slicePathCustom;

wheel1.clickModeRotate = true;
wheel2.clickModeRotate = false;
wheel1.navAngle = 90;
wheel2.navAngle = 90;
wheel1.titleRotateAngle = -90;
wheel1.animatetime = 400;
wheel1.animateeffect = 'linear';
wheel1.initTitleRotate = true;
wheel1.clockwise = false;
wheel1.rotateRound = true;
wheel1.createWheel();
wheel2.createWheel(['^']);

var wheelspreader = document.getElementById("wheelnav-wheelDiv-spreader");
var wheelspreadertitle = document.getElementById("wheelnav-wheelDiv-spreadertitle");
wheelspreader.onmousedown = function() {openSpreader();}
wheelspreadertitle.onmousedown = function() {openSpreader();}

wheel1.animateFinishFunction = onClick;
 function onClick() {
 if (wheel1.currentClick == 0) {
 $("#loading").css("display", "block");
 window.location.href="/pages/thaaval.html";
 } else if (wheel1.currentClick == 1) {
 $("#loading").css("display", "block");
 window.location.href="/pages/about.html";
 } else if (wheel1.currentClick == 2) {
 $("#loading").css("display", "block");
 window.location.href="/pages/phonelist.html";
 }
 }
});
var openSpreader = function() {
  wheel1.minPercent = wheel1.maxPercent;
}
</code>

Here is my js code

**Comment by elvis7449** [comment]
The div's:

<code>
<div id="wheelDiv" data-wheelnav data-wheelnav-cssmode data-wheelnav-titlewidth="70" data-wheelnav-titleheight="70" data-wheelnav-init>
<div data-wheelnav-navitemimg='wheelnav/thaavalT.png'></div>
<div data-wheelnav-navitemimg='wheelnav/aboutT.png'></div>
<div data-wheelnav-navitemimg="wheelnav/ehenihenphoneT.png"></div>
<div data-wheelnav-navitemimg='wheelnav/kureegethaavalT.png'></div>
<div data-wheelnav-navitemimg='wheelnav/hushahalhaaT.png'></div>
<div data-wheelnav-navitemimg='wheelnav/baakyT.png'></div>
</div>

<div id="wheel2" data-wheelnav data-wheelnav-cssmode data-wheelnav-init></div>
</code>

**Comment by elvis7449** [comment]
<div id="wheelDiv" data-wheelnav data-wheelnav-cssmode data-wheelnav-titlewidth="70" data-wheelnav-titleheight="70" data-wheelnav-init>
<div data-wheelnav-navitemimg='wheelnav/thaavalT.png'></div>
<div data-wheelnav-navitemimg='wheelnav/aboutT.png'></div>
<div data-wheelnav-navitemimg="wheelnav/ehenihenphoneT.png"></div>
<div data-wheelnav-navitemimg='wheelnav/kureegethaavalT.png'></div>
<div data-wheelnav-navitemimg='wheelnav/hushahalhaaT.png'></div>
<div data-wheelnav-navitemimg='wheelnav/baakyT.png'></div>
</div>

<div id="wheel2" data-wheelnav data-wheelnav-cssmode data-wheelnav-init></div>

**Comment by elvis7449** [comment]
Sorry. Its kinda messed up. Idk jsfiddle things. Hope yu understand

**Comment by softwaretailoring** [comment]
Sorry, I cannot reproduce your issue based on above code...
Please add your working version to https://jsbin.com
Or send all of your source code to me via email. (You can find my email address on my GitHub profile)

**Comment by elvis7449** [comment]
okay here it is:

https://jsbin.com/jipavahavu/edit?html,css,output

**Comment by elvis7449** [comment]
it seems to me that when i lower wheel1.animatetime to 300ms, it works for 2 to 3 continuous clicks until it again jumps to a wrong slice.

P.S: I am using jquery in my website and this problem only occurs to me in IOS mobile safari. Thank you

**Comment by elvis7449** [comment]
Any idea how to set navitem img dynamically? 
I tried initWheel wid imgsrc and then refreshing. But it doesn't work

**Comment by softwaretailoring** [comment]
Please try with this version of raphael.js:

`<script src="https://cdn.jsdelivr.net/npm/wheelnav@1.7.1/js/dist/raphael.min.js"></script>`

**Comment by elvis7449** [comment]
Cool, will give you an update after trying.. Cheers

**Comment by elvis7449** [comment]
Sorry to say with that version also the same thing is happening :(

**Comment by softwaretailoring** [comment]
Hmm... Unfortunately I cannot reproduce your issue in my environment. I have desktop Safari on Windows.

I think the wheel2 is unnecessary. You can achieve same result (and better performance) via `wheel1.raphael.image("donut.svg", 0, 0, 400, 400);`

Do you have same issue on a simpler wheelnav? For example: http://wheelnavjs.softwaretailoring.net/documentation/core.html#sectionProperties

**Comment by elvis7449** [comment]
Actually the wheel2 is for that border only.. ;-) Any simple way to make such border? 
Nope i haven't tried a simple one. Will try and let you know.

**Comment by softwaretailoring** [comment]
"Any simple way to make such border?"
`wheel1.raphael.image("donut.svg", 0, 0, 400, 400);`
Where donut.svg is the border image.

**Comment by elvis7449** [comment]
So this is how i see it:
https://jsbin.com/xazuyanizo/edit?output

**Comment by softwaretailoring** [comment]
Here is a better version:

`wheel1.raphael.path("M200,20L200,0A200,200,0,0,1,200,400A200,200,0,0,1,199.99999999999997,0L199.99999999999997,20A180,180,0,0,0,200,380A180,180,0,0,0,200,20Z").attr({"fill":"#f58866","stroke-width":"0"});`

https://jsbin.com/tuwigakugu/edit?js,output

**Comment by elvis7449** [comment]
Thank you so much. But still that wrong selection issue isn't solved. You may close this issue though 👌

**Comment by softwaretailoring** [comment]
I'm sorry. Were you able to check a simpler wheelnav?
It would be good to know that IOS mobile Safari doesn't supported at all or only with restriction.

**Comment by Mubashirkhan** [comment]
was any one able to solve this issue on mobile. I'm trying to use this plugin in a react native app but it doesn't work on the in app webview browser. Any ideas how we can fix that issue
