### ISSUE TITLE
How to change slice navitemimg dynamically...? 

### ISSUE THREAD

**Issue by elvis7449** [softwaretailoring/wheelnav#64]
Is there a way to change one slice img dynamically?

**Comment by softwaretailoring** [comment]
Yes. You can modify a slice title to its initial type.

In case of image:
```
wheel.navItems[0].setTitle("imgsrc:http://softwaretailoring.net/wheelnavjs/images/twitter.png");
wheel.refreshWheel(true);
```
Here is a [JSBin](https://jsbin.com/rehefav/edit?html,js,output) for that.

**Comment by elvis7449** [comment]
Oh, previously refreshWheel doesnt have boolean feature right?

**Comment by elvis7449** [comment]
so why dont this work:

<code>
wheel.spreader.outTitle.title = 'imgsrc:wheelnav/unlocked.png';
wheel.refreshWheel(true);
</code>

**Comment by elvis7449** [comment]
And btw, when i try with your method it doesn't work for me unless i select some other slice.. 
In my case firstly there will be some blurred slices and when user log in the slice image changes.
so in a if case i use
<code>

if (currentUser) {

  wheel.navItems[0].setTitle("imgsrc:http://softwaretailoring.net/wheelnavjs/images/twitter.png");

  wheel.refreshWheel(true);

}

</code>

But my code doesn't work unless i press some other slice. but again after refreshing the page it shows previous icons

**Comment by elvis7449** [comment]
Here is my original code for that:

`
if (currentUser) {
  loadWheel(); // this is the original wheel function
  wheel1.navItems[0].setTitle("imgsrc:wheelnav/thaavalT.png");
  wheel1.navItems[3].setTitle("imgsrc:wheelnav/kureegethaavalT.png");
  wheel1.navItems[4].setTitle("imgsrc:wheelnav/hushahalhaaT.png");
  wheel1.navItems[5].setTitle("imgsrc:wheelnav/baakyT.png");
  // wheel1.spreader.outTitle.title("imgsrc:wheelnav/unlocked.png");
  wheel1.spreader.outTitle.title = 'Log Out';
  wheel1.refreshWheel(true);
} else {
  loadWheel();
}`

where am i going wrong? thanks for your help 👍

**Comment by softwaretailoring** [comment]
`wheel1.spreader.outTitle` is a [raphael object](http://dmitrybaranovskiy.github.io/raphael/reference.html#Paper.image) so you can modify its src property in case of image.

The code below is wrong.
`wheel1.spreader.outTitle.title("imgsrc:wheelnav/unlocked.png");
wheel1.spreader.outTitle.title = 'Log Out';`
There is no title() function in outTitle. And you can modify title into its initial type. Text to text, svg path to svg path, image to image.

**Comment by elvis7449** [comment]
Yeah i couldn't get it working. Thats why i have commented it. I can update title of the spreader, but not the image of it. So my concern here is i could not set spreader and slice title image dynamically using your code :-)
