### ISSUE TITLE
how to make donutslice thinner

### ISSUE THREAD

**Issue by devJoshLopez** [softwaretailoring/wheelnav#65]
How can I make the donutslices thinner? I have the spreader disabled but I want to make the middle of the wheel bigger.

Wheelnav is awesome!

**Comment by softwaretailoring** [comment]
Hi @devJoshLopez 
Thanks!
You can modify your path via customization: http://wheelnavjs.softwaretailoring.net/documentation/slicePath.html#customization
There is a DonutSliceCustomization for your needs: https://github.com/softwaretailoring/wheelnav/blob/v1.7.1/js/source/slicePath/wheelnav.slicePath.Donut.js
