### ISSUE TITLE
Curved NavItem Text

### ISSUE THREAD

**Issue by aashish-snp** [softwaretailoring/wheelnav#68]
Hi,

We are trying to embed curved nav item text in a multi layered wheel. However we are not able to achieve the curving effect.

We would require a solution to curve text contents with respect to path, just like mentioned in link below. 

https://css-tricks.com/snippets/svg/curved-text-along-path/

Please help us to sort out the problem, it would help us immensely as we have text contents with higher lengths in navitem.

Thanks in anticipation.

**Comment by softwaretailoring** [comment]
Hi @aashish-snp 

Unfortunately, the curved text functionality doesn't supported currently. There is an open issue for that: #4 

However, you can achieve your needs with predefined SVG titles. I suggest that you create SVG files for titles with curved text and use these files as an image on NavItem.

`wheel.createWheel(['imgsrc:title1.svg', 'imgsrc:title2.svg', 'imgsrc:title3.svg', 'imgsrc:title4.svg']);`
