### ISSUE TITLE
reset raphael sub nav wheel

### ISSUE THREAD

**Issue by wessykes** [softwaretailoring/wheelnav#69]
Happy new year everyone.

Could someone give me some help with resetting a sub navigation  wheel ? I have successfully created a wheel that displays another wheel around its exterior when a slice has been selected.

Unfortunately. when I need the content of the second wheel to change, it doesnt. 

How can I remove or refresh wheel 2 when I have chosen an option in wheel 1?
Regards

We

**Comment by softwaretailoring** [comment]
Hi @wessykes 

There are two methods for that:

```
wheel.refreshWheel(true); // false: only style affected, true: path and transform also
wheel.removeWheel();
```

You can try these methods [here](http://wheelnavjs.softwaretailoring.net/documentation/core.html) under Methods section.

**Comment by wessykes** [comment]
Thanks for this Gabor :)

I spent ages finding a work around with code but I will give these a try today.

Another problem I am having is stopping the donut slice expanding after selection. When I do slicePathCustom.minRadiusPercent = 0.6 I get the correct thickness of donut. But after selecting the slice the section reverts back to its original thickness before the custom radius percentage.

Regards

Wes

**Comment by wessykes** [comment]
Thought this may help explain my last email. Thanks again for your support.

​

**Comment by wessykes** [comment]
Gabor.
Sorry to be a pain.

Ignore my last 2 emails I have figured it out now.

Happy new year to you :)

Wes
