### ISSUE TITLE
Clockwise rotation only?

### ISSUE THREAD

**Issue by niksnair** [softwaretailoring/wheelnav#70]
Hey, first of all thank you for this great plugin. I am using this plugin for one of my clients website. The requirement is to have only clockwise rotation of the wheel. Currently the wheel rotates both ways. Is there any option which keeps the rotation of wheel clockwise only?

Thank you.

**Comment by softwaretailoring** [comment]
Hi @niksnair 

Try this:
```
wheel.clockwise = false; //order of navItems
wheel.rotateRound = true; //keeps the rotation
```
May I check your website with wheelnav?

**Comment by niksnair** [comment]
Hey, thank you for the answer. It worked! 
Currently I am building it locally. Will update with link once done. 

A quick question: Is it possible to put an image in the center of Donut slice path?

**Comment by softwaretailoring** [comment]
Good question, I've created a new thread for it and answered there.
#71
