### ISSUE TITLE
Demo code for Sub Menu example

### ISSUE THREAD

**Issue by mattbryson** [softwaretailoring/wheelnav#73]
Hi, Is there demo code for the Sub menus example? or a demo project?

I need to implement 2 levels of submenus, but cant see how this is achieved.

http://wheelnavjs.softwaretailoring.net/examples.html#subWheel

**Comment by softwaretailoring** [comment]
Hi  @mattbryson 
Please check issue #31

**Comment by mattbryson** [comment]
Thanks @softwaretailoring , thats really helped, got a 2 level menu going on now.

There is another problem I have hit - I cant see how to add / remove items to an existing wheel?  Is this possible, even removing All the items and re rendering would work for me?

I cant use `remove` as all the nested wheels share the same `raphael` instance, so all wheels are removed.

**Comment by mattbryson** [comment]
Incase anyone else finds this, the way I got round it was to NOT create each sub menu as a child of the root.  Instead I had 3 totally independent menus, which then meant I could destroy and recreate them on the fly individually.

**Comment by softwaretailoring** [comment]
You are right, there is no removeNavItem method currently, only removeWheel.

Thank you for you sharing your experience with independent menu solution!
