### ISSUE TITLE
Can a nav be dragged?

### ISSUE THREAD

**Issue by mattbryson** [softwaretailoring/wheelnav#74]
As well as clicking an item and it rotating to the selected position, can the wheel be dragged on touch interface to the selected position?

**Comment by softwaretailoring** [comment]
Unfortunately, dragging is not supported currently.

**Comment by mattbryson** [comment]
No, didn't think it would be.  What are your thoughts on how easy this would be to achieve?

Once I have the project sorted, ill have a look at implementing it  - Ive done a lot of stuff with touch / dragging but never with SVG elements.  I assume its going to be pretty hard as SVG calculates the animation for us.

I suppose I would first need to create a method that could manually position the wheel and titles etc based on an angle?  I assume there is nothing in the lib already like this?

**Comment by softwaretailoring** [comment]
Yes, there is no such code in the library.
I assume this would be a little bit complicated, but not pretty hard.
