### ISSUE TITLE
Spinning wheel on touch

### ISSUE THREAD

**Issue by dilby** [softwaretailoring/wheelnav#75]
Is there a way to make the wheel spin (not must moving it to the segment you click) by dragging it with touch or cursor up and down (some sort of physics involved would be awesome.)

**Comment by softwaretailoring** [comment]
Currently, the library doesn't support dragging.
However, you can use the keyboard to spin. More info here: http://wheelnavjs.softwaretailoring.net/documentation/core.html#sectionKeynav
