### ISSUE TITLE
z-index two wheels

### ISSUE THREAD

**Issue by yoan1005** [softwaretailoring/wheelnav#77]
Hi, 
I use your plugin for make a menu, after 2 days i have almost solved all my problems, but one persist.
I have many wheels, and when i click on main wheel, the corresponding wheel appear. It's work but i would like that the main wheel are always on top by other like z-index : 10 for main wheel and all others sub wheel are z-index 1,2,3,4……

The example here, the blue is main wheel and red are sub wheel. 
https://jsfiddle.net/je5juLvg/

Can do that you think ?
Thaaank !
sry for my english

**Comment by softwaretailoring** [comment]
Hi @yoan1005 
You can achieve it via JavaScript: `wheel1.navItems[0].navSlice.toFront();`

**Comment by softwaretailoring** [comment]
You must use it inside navigateFunction: https://jsfiddle.net/je5juLvg/4/

**Comment by yoan1005** [comment]
Ohhh perfect ! thanks u !
