### ISSUE TITLE
Two rotating wheels

### ISSUE THREAD

**Issue by davesade** [softwaretailoring/wheelnav#80]
Hello!
In your example of advanced constructor, you show the code, where you pass `wheel1.raphael` as second parameter to `wheel2` object.
However, I couldn't figure out, how you did achieved total synced rotation of both wheels.
My idea is to have second wheel purely for cosmetic effect, when user selects an item from top wheel.

I tried this:

```
wheel1.navItems[0].navigateFunction = function() {
  wheel2.navigateWheel(0);
};
```

This "kinda works", but only one way. I was hoping, that whole point of using wheel1.raphael was to transfer rotation of one wheel to another.

I looked up into the source code of the page http://wheelnavjs.softwaretailoring.net/documentation/core.html but I was unable to dig out the code for it.

Any advice appreciated!

**Comment by softwaretailoring** [comment]
Hi @davesade 

Sorry for late response, summertime. :)
The second wheel is not for cosmetic purpose.
You can use it:
```
wheel2.navItems[0].navigateFunction = function() {
  wheel1.navigateWheel(0);
};
```
