### ISSUE TITLE
Touch control

### ISSUE THREAD

**Issue by neongrau** [softwaretailoring/wheelnav#82]
Touch control so you could spin it by swiping.

**Comment by softwaretailoring** [comment]
Nice idea! I've attached it to drag enhancement. #78

**Comment by xgqfrms** [comment]
I'm also seeking for a solution for drag rotate menu.

> partly demo

https://codepen.io/xgqfrms/pen/MMeNxr

> update, demo

https://codepen.io/xgqfrms/pen/qzaKQE
