### ISSUE TITLE
Usage in VueJS application

### ISSUE THREAD

**Issue by humblecoder** [softwaretailoring/wheelnav#85]
I'm trying to integrate this into a VueJS project using single file components.  In my `main.js` I am importing the library with `require('wheelnav')` and it seems to import correctly.  However, whenever I attempt to use it (per the demo), I receive the following errors:

1)  `colorpallette not defined` **I remove the line**
2)  `icon not defined` **I  substitute strings**
3)  `cannot read property 'length' of undefined`

A bit more information on what each of these items is and where they come from might be helpful.  Of course, it's possible you've placed it in the docs and I've missed it.  🤔

**Comment by humblecoder** [comment]
Unfortunately the source is in a private repo.  😖  However, if I can steal some time in the next little bit I'll see if I can't get it working in a "clean" app.

**Comment by softwaretailoring** [comment]
I don't know any public Vue component.
