### ISSUE TITLE
Error: <path> attribute d: Expected number, "M,0,0".

### ISSUE THREAD

**Issue by ChristianBielak** [softwaretailoring/wheelnav#86]
Hi,

i'm try to use wheelnav js with Vue.js and typescript. Finally i got it running but now when the nevaigation is created, i get the error

Error: <path> attribute d: Expected number, "M,0,0".

Would be glad if someone has a solution.

Thanks for help :)

Chris

**Comment by softwaretailoring** [comment]
Hi Chris,

What type of raphael do you use?
I suggest this:
`<script src="https://cdn.jsdelivr.net/npm/wheelnav@1.7.1/js/dist/raphael.min.js"></script>`

And you can find wheelnav on jsdelivr also: https://www.jsdelivr.com/package/npm/wheelnav

**Comment by ChristianBielak** [comment]
Hi,

currently I'm using 2.2.7. I'll try your suggested version. Thanks for your fast reply.

**Comment by jodybrabec** [comment]
The following works for me.
In raphael.js, REPLACE:
	el.setAttribute(key, Str(attr[key]));
WITH:
	var strValue = Str(attr[key]);
	if (key === "d" && strValue === "M,0,0") {
		strValue = "M0,0";
	}
	el.setAttribute(key, strValue);

**Comment by hadasmaimon** [comment]
in my case, the arrow line was smaller than the arrow-end triangle,
so I set the min size of the path to be 11
`var subPathStr = guidePath.getSubpath(0, Math.max(11, thisLength));`
