### ISSUE TITLE
Sub menu click not working when using Curvetext functionality

### ISSUE THREAD

**Issue by Sibinraj** [softwaretailoring/wheelnav#88]
I have created a 3 level menu using wheelnav.js and it was working fine. Now I have updated the js version to 1.8.0 for implementing the curve text functionality. Unfortunately, now the click on the second level menu is not working smoothly.
Demo is here https://jsbin.com/calajud/edit?html,js,output
I have posted the same on Stackoverflow
https://stackoverflow.com/questions/55243617/wheelnav-menu-click-not-working-when-using-curvetext-functionality

**Comment by softwaretailoring** [comment]
Hi @Sibinraj 
I've analyzed your issue and unfortunately, I don't have any idea to solve this.

As I see, the titlepath covers other elements:

![image](https://user-images.githubusercontent.com/6381084/55019408-1df9c200-4ff5-11e9-9511-76b4b90a90db.png)

Maybe the solution is [here](https://github.com/softwaretailoring/wheelnav/blob/v1.7.1/js/dist/wheelnav.js#L1327)

I would like to note that v1.8.0 is only a release candidate.

**Comment by Sibinraj** [comment]
Thanks I fixed this issue by making the path display none.
I have added two line code inside the addCurvedTitle function.  Now the click issue is resolved.
 **var thispathnode = document.getElementById(pathid);
 thispathnode.setAttribute("style", thispathnode.getAttribute("style") + ";display:none;");**

**Comment by Sibinraj** [comment]
Now I am facing another issue with Arabic text. 
How I will add the arabic text with curvetext functionality? Your answer will be very helpful
