### ISSUE TITLE
The Arabic text is not rendering correctly when using Curvetext functionality

### ISSUE THREAD

**Issue by softwaretailoring** [softwaretailoring/wheelnav#91]
From the end of #88 
"Now I am facing another issue with Arabic text. In google chrome the Arabic text is not rendering correctly.
How I will add the arabic text with curvetext functionality?
Your answer will be very helpful
I have updated demo with Arabic text https://jsbin.com/calajud/edit?html,js,output"

**Comment by softwaretailoring** [comment]
Hi @Sibinraj
Does this issue still exist?
As I see, the Arabic text rendering correctly in your demo.

**Comment by elvis7449** [comment]
> Hi @Sibinraj
> Does this issue still exist?
> As I see, the Arabic text rendering correctly in your demo.

Nope. If you see clearly those Arabic texts are in our order. Arabic should be in rtl order right. I'm facing same issue as I use a rtl font. The font also get formatted.
