### ISSUE TITLE
Change Path of 'data-wheelnav-navitemimg' SVG by CSS

### ISSUE THREAD

**Issue by RonMen** [softwaretailoring/wheelnav#96]
Hey there,

I can not access an SVG image element of a navitem via CSS to set e.g. fill of path on mouseover since using "data-wheelnav-navitemimg" with SVG as a source is only provided as "image" element. Anything to do to make it working?

Regards
RonMen

**Comment by softwaretailoring** [comment]
Sorry for the late response. Do you still have this issue?

**Comment by EphraimB** [comment]
Re-open it. I'm having this problem with my downloaded google material icons and want it switched to white from black on selected.
