### ISSUE TITLE
Errors in Wheelnav.js, missing semikolon

### ISSUE THREAD

**Issue by MdmrBerlin** [softwaretailoring/wheelnav#97]
Line 1990 and 3704 are semikolons missing.

There is also an problem on minifi with webpack to bundle it.
No funtion is exported.

**Comment by softwaretailoring** [comment]
Hi @MdmrBerlin 

Thanks for missing semicolons, it fixed.

I don't use Webpack, so I cannot test your bundle issue.
However, the bundling process has been changed, maybe it works with Webpack now.
