### ISSUE TITLE
mouseup Event Not Firing Randomly

### ISSUE THREAD

**Issue by muratzki** [softwaretailoring/wheelnav#99]
Thank you for wheelnav.js! However, I am having an apparently random problem of the the mouseup event on a slice not firing. You can click slices on the wheel maybe 20 times, and all slices will work properly, Then, one click will not work. The wheel rotates the clicked slice into the first position, but the mouseup event does not run. Any ideas on this would be greatly appreciated.

This implementation is on this website (still in development): http://dev.liaa.org/nrcareers

Here is the initialization code I'm using for the wheel. 3rd line from the end is where the event is set. When the problem happens, the function specified does not run.
			//build the wheel
			crWheel = new wheelnav('crwheelit');
			crWheel.colors = new Array('#193682', '#00A29D', '#00AAE2', '#913690');
			crWheel.titleAttr = { fill: '#FFFFFE', font: '400 1em "Open Sans", sans-serif' };
			crWheel.titleHoverAttr = { fill: '#FFFFFE', font: '400 1em "Open Sans", sans-serif' };
			crWheel.titleRotateAngle = 0;
			crWheel.sliceSelectedTransformFunction = sliceTransform().MoveMiddleTransform;
			crWheel.sliceSelectedAttr = { fill: '#FF9900' };
			crWheel.titleSelectedAttr = { fill: '#000001' };
			crWheel.clockwise = false;
			crWheel.animatetime = 1000;
			var crWItems = [];
			for (var i = 0; i < crWData.careers.length; i++) {
				crWItems.push(crWData.careers[i].careername);
			}
			crWheel.initWheel(crWItems);
			crWheel.createWheel();
			for (i = 0; i < crWheel.navItems.length; i++) {
				crWheel.navItems[i].navSlice.mouseup(function(){crSelCareer(crGetIndexFromID($(this)[0].id));});
			}
			crWheel.refreshWheel();

Thank you!

**Comment by softwaretailoring** [comment]
Weird problem.
I cannot reproduce this now.
Does this issue still exist?

The URL redirects to https://www.nwmicareers.org/

**Comment by muratzki** [comment]
Thank you for responding to my question! Since launching the site to https://www.nwmicareers.org this problem has become inexplicably less frequent, since the code did not change. During the weeks of development, it often happened. I'll close this now with the hope that it is gone for good.

Thank you for access to your amazing work!
